### ISSUE TITLE
Issue when using alternate port

### ISSUE THREAD

**Issue by mwareman** [bpaauwe/WeatherFlow#2]
Somewhere in code, it's still trying to use the standard port:

`2018-7-7 22:28:18 - error: NSChild STDERR: WeatherFlowPoly: events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:50222
    at _handle.lookup (dgram.js:282:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at _handle.lookup (dgram.js:283:14)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

I have the parameter set for an alternate port (50227) - as I have LogStash listening on the standard port for logging to Elasticsearch purposes. LogStash is forwarding to the alternate port for this Polyglot to pick up and send to ISY:

`MQTT connection with Polyglot has been started.
MQTT host connected
MQTT connection has been configured
in ConfiguredNodes
ISY version: 5.0.12
We have a config from Polyglot
Name       : WeatherFlowPoly
  Listening UDP Port  : 50227
  Using units: US
customParams = {"Elevation":"675","Units":"US","ListenPort":"50227"}
  Elevation  : 675
newParams    = {"Elevation":"675","Units":"US","ListenPort":"50227"}`

**Comment by bpaauwe** [comment]
I have not been able to reproduce this. I did add some additional logging to display the port number being used in the bind call and some error trapping for the bind call.

There is only one place in the code where the UDP port is used and that is the single bind call. The only possible case I can think of is that the bind was called with the default port before the configuration was changed to set the new port number. If this is the case, restarting the node server should resolve the issue.
